from typing import TypedDict, List, Dict

class AgentState(TypedDict):
    """
    Represents the state of our LangGraph agent.
    """
    task: str               # The original user research task
    queries: List[str]      # Search queries generated by the agent
    urls: List[str]         # URLs gathered from searches
    scraped_data: Dict[str, str]  # Scraped data content mapping URL -> clean text
    current_loop: int       # Iteration count to prevent infinite loops
    next_action: str        # Tells the routing edge where to go ('continue' or 'write')
    report: str             # The final written markdown report
    logs: List[str]         # Step-by-step log of agent execution for UI rendering
